
public class TesteExcecao {
	
	public static void main(String[] args) {
		
		
		
		/*try {
		int a = 10, b = 0;
		int [] ar = new int[3];
		ar[4] = 10;
		Estudante est = null;
		est.exibir();
	}
    catch(ArithmeticException e) {
    	System.out.println("deu erro : na divisao por zero");
    }
	catch(ArrayIndexOutOfBoundsException e) {
		System.out.println("deu erro : indice fora dos limites");
	}
	catch(NullPointerException e) {
		System.out.println("deu erro : erro de ponteiro nulo");
	}
	catch(Exception e) {
		System.out.println("deu erro : erro desconhecido");
	}
	System.out.println("continuando depois do try-cast");
	*/
}
}
		